server:
  port: 12345

spring:
  dubbo:
    application:
      name: demo-consumer
      logger: slf4j
      owner: konglingzhen
      organization: wsd-java
    zkRegistry:
      address: zookeeper://registry.zookeeper.me:2181
    redisRegistry:
      address: redis://registry.redis.me:6379
    dubboProtocol:
      name: dubbo
      port: 30800
    monitor:
      protocol: registry
    version: 0.0.1
    group: dev

logging:
  level:
    root: info

